### ISSUE TITLE
[ERROR] Failed to initialize the device: Error: Failed to run the GetProfiles() method: Error: socket hang up

### ISSUE THREAD

**Issue by espizo** [futomi/node-onvif#12]
Getting this error with a Hikvision camera using this code:

```javascript
#!/usr/bin/env node

var onvif = require('./lib/node-onvif.js');

// Create an OnvifDevice object
var device = new onvif.OnvifDevice({
  xaddr: 'http://some.host:8080/onvif/device_service',
  user : 'username',
  pass : 'password'
});

// Initialize the OnvifDevice object
device.init((error) => {
  if(error) {
    console.log('[ERROR] ' + error.message);
  } else {
    console.log('The OnvifDevice object has been initialized successfully.');
    // Do something.
  }
});
```

**Comment by DonMehdi** [comment]
May be it is due the fact that onvif is not enabled on the camera

**Comment by futomi** [comment]
Sorry for the delay in getting back to you. I missed your feedback.

> May be it is due the fact that onvif is not enabled on the camera

That does not cause "socket hang up", I think.
What is your node version?
If possible, try with node 6+.

**Comment by DonMehdi** [comment]
i have version v7.6.0, ok i'll try with 6+

**Comment by DonMehdi** [comment]
actually  i have an axis camera and it workerd pretty well, but not with the bosch mic 7000 hd.

**Comment by futomi** [comment]
> i have version v7.6.0, ok i'll try with 6+

V7 is good. You don't need to try with v6.

> actually i have an axis camera and it workerd pretty well, but not with the bosch mic 7000 hd.

It seems that the problem depends on the product.
I wonder if the bosch mic 7000 hd disconnects a TCP session.
For now, I don't have any solution.

**Comment by futomi** [comment]
I updated the node-onvif.
Though I'm not sure the latest version solves this issue, try it.

Cheers,
Futomi

**Comment by hawkeye64** [comment]
My pull request may fix this issue
