### ISSUE TITLE
node-onvif vs. onvif

### ISSUE THREAD

**Issue by espizo** [futomi/node-onvif#13]
There is another node module named onvif here: https://github.com/agsh/onvif/

Do you know anything about this module, and if so, how would you compare it to your module?

Pros/cons, etc.

**Comment by futomi** [comment]
I did not know [the module](https://github.com/agsh/onvif/).

As far as I read [the documentation of the module](https://github.com/agsh/onvif/), it seems to expose pretty much similar APIs to the [node-onvif](https://github.com/futomi/node-onvif). I think that you can achieve what you want using both [the onvif](https://github.com/agsh/onvif/) and the [node-onvif](https://github.com/futomi/node-onvif). The difference is the coding style. 

The [onvif](https://github.com/agsh/onvif/) module seems to support the Profile G (Replay). It is an advantage of the [onvif](https://github.com/agsh/onvif/) module. The [node-onvif](https://github.com/futomi/node-onvif) module does not support the Profile G. Though I'm not familiar with the Profile G, If you want to use the Profile G, you should use the [onvif](https://github.com/agsh/onvif/)module.
