### ISSUE TITLE
404 not found on fetchSnapshot

### ISSUE THREAD

**Issue by Zombitch** [futomi/node-onvif#14]
Hi,

When I request a snapshot I get 404 Not found error as below (I'm using only example provided in the doc) :

```
fetching the data of the snapshot...
Error: 404 Not Found
    at IncomingMessage.res.on (/home/zombitch/Developpement/thor/node_modules/node-onvif/lib/modules/device.js:207:13)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

Regard,
Zombitch

**Comment by Zombitch** [comment]
I dont know why, but it seems the snapshot URI for my cam is something like : 

'http://www.gwelltimes.com/manage/Upload/Pic/20147914514701.jpg'

**Comment by futomi** [comment]
> I dont know why, but it seems the snapshot URI for my cam is something like :
> 
> 'http://www.gwelltimes.com/manage/Upload/Pic/20147914514701.jpg'

Wow, it's impossible. Basically, the snapshot URL should point to the cam itself. The URL you got seems to be a global address. I hope your cam is not infected. You should ask the seller or the manufacturer of your cam whether that is normal or not.

**Comment by Zombitch** [comment]
Yes thats was I thought about it is impossible, I contacted the manufacturer and I will jeep this topic up tout date. Thanks.

**Comment by Zombitch** [comment]
Well, the manufacturer support has just answered me the following : 

> GetSnapshotUri is not supported by this cam...

Conclusion : Do not buy Hikam A7 camera if you plan to use ONVIF protocol.

**Comment by futomi** [comment]
Thank you for your information.
