### ISSUE TITLE
Sample doesn't support two cameras

### ISSUE THREAD

**Issue by kodonnell** [futomi/node-onvif#26]
I have two IP cameras and can have them both running at the same time through their own GUIs. However, I cannot connect to both from the sample app in this repo. If I'm connected to A, and then open up a new tab and connect to B, the connection to B now works, but A is frozen. Likewise if I reconnect A. Any ideas on what might cause this? (Websockets?) Is it designed to support multiple, or only one?

**Comment by futomi** [comment]
Unfortunately, the sample app "ONVIF Network Camera Manager" does not support multiple streams.

**Comment by jensysantana** [comment]
hi, did you solver your problem?
