### ISSUE TITLE
Event service usage

### ISSUE THREAD

**Issue by bartbutenaers** [futomi/node-onvif#32]
Hi Futomi (@futomi),

I need your help once again ...  
My (OnVif) IP camera's have a PIR detector, so I would like to receive events as soon as motion is detected.  

Did some reading about it and it seems that WS notifications are being used in OnVif to accomplish this.  Can I use perhaps your [service-events.js](https://github.com/futomi/node-onvif/blob/master/lib/modules/service-events.js) for this purpose?  

When I get the available services from my camera, it _'looks'_ to me that the event service is available:

![image](https://user-images.githubusercontent.com/14224149/40590283-9d4a0ec6-61fc-11e8-8de5-31b7722d6ce0.png)

Thanks in advance for your time !!

Bart Butenaers

**Comment by futomi** [comment]
Yes, I actually tried to implement the ONVIF event. Unfortunately, I could not accomplish that. I could not receive events from my own ONVIF cameras. For now, I don't know how to receive events.

Sorry for that. Though I'm busy now, I'll try again in future.
