### ISSUE TITLE
The WebSocket connection was closed

### ISSUE THREAD

**Issue by StefanRu1** [futomi/node-onvif#7]
Hi,

thanks for your help.
I now use:
node -v
v4.4.2

I am running on an rasspberry pi 3.

After starting and seeing the UI i get a POP up with:
Error
The WebSocket connection was closed. Check if the server.js is running.

The Server shows:
Listening on port 8880
HTTP : 200 OK : /
HTTP : 200 OK : /style.css
HTTP : 200 OK : /onvif.js

Do you have an idea?

Thanks,
Stefan

**Comment by futomi** [comment]
What web browser did you use? I recommend the latest raspbian and the pre-installed chromium.

Though I tried RASPBIAN JESSIE WITH PIXEL + node v6 before, I accessed the server.js with PC remotely at that time. I did not try to use the pre-installed chromium on the Raspberry Pi 3. But I think that the spec of Raspberry PI 3 is too poor to run the server.js and the web application on the chromium on it.

**Comment by StefanRu1** [comment]
Hi,
i use Rapberry PI3 and access the webserver server.js from a Windows PC with google chrome.
But also internet explorer did not work.

Should i use chromium on the repberry?

Best regards,
Stefan

**Comment by futomi** [comment]
> i use Rapberry PI3 and access the webserver server.js from a Windows PC with google chrome.
> But also internet explorer did not work.

Were any errors reported in the console of the google chrome? If any, can you give me the errors?

> Should i use chromium on the repberry?

No. I recommend to use the google chrome on your Windows PC.

**Comment by StefanRu1** [comment]
Hi futomi,

thanks for your answer.

In the console of chrome i have:
http://192.168.69.94:8880/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

onvif.js:89 WebSocket connection to 'ws://localhost:8880/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

OnvifManager.initWebSocketConnection @ onvif.js:89
onvif.js:95 WebSocket connection closed.

The first one 404 is just because of not present favicon. this should not matter.
The rest i do not know. It seems ws on 8880 is not working?

I connect on chrome to my raspberry with:
http://192.168.69.94:8880/

Thanks and best regards,
Stefan

**Comment by futomi** [comment]
Thanks for your support.
I found the bug and fixed it.
Try the latest version of the node-onvif.
You can now use the `npm` command to update the node-onvif to the latest version.

**Comment by StefanRu1** [comment]
Hi futomi,
thank you so much! Works like a charm now.

Best regards,
Stefan
