### ISSUE TITLE
"profiles.forEach is not a function" exception

### ISSUE THREAD

**Issue by tosscaster** [futomi/node-onvif#8]
OnvifDevice.prototype._mediaGetProfiles = function(callback) {

....
profiles.forEach((p) => {   <== exception

events.js:163
      throw er; // Unhandled 'error' event
      ^

TypeError: profiles.forEach is not a function
    at OnvifDevice._mediaGetProfiles.callback.services.media.getProfiles (g:\Nodeproject\onvif\node-onvif\lib\modules\device.js:385:12)
    at OnvifServiceMedia.getProfiles.mOnvifSoap.requestCommand (g:\Nodeproject\onvif\node-onvif\lib\modules\service-media.js:312:3)
    at OnvifSoap.requestCommand.callback._request.parse (g:\Nodeproject\onvif\node-onvif\lib\modules\soap.js:71:8)
    at OnvifSoap.parse.mXml2Js.parseString (g:\Nodeproject\onvif\node-onvif\lib\modules\soap.js:39:3)
    at Parser.<anonymous> (g:\Nodeproject\onvif\node-onvif\node_modules\xml2js\lib\xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
    at SAXParser.onclosetag (g:\Nodeproject\onvif\node-onvif\node_modules\xml2js\lib\xml2js.js:447:26)
    at emit (g:\Nodeproject\onvif\node-onvif\node_modules\sax\lib\sax.js:640:35)

-> looks like profiles is not array but object.

with soap message below
----
"<?xml version="1.0" encoding="UTF-8" ?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope"
xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex"
xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#"
xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:wsc="http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512"
xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include"
xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2"
xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2"
xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl"
xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2"
xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl"
xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics"
xmlns:ter="http://www.onvif.org/ver10/error">
  <SOAP-ENV:Header></SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <trt:GetProfilesResponse>
      <trt:Profiles token="profile1" fixed="true">
        <tt:Name>profile1</tt:Name>
        <tt:VideoSourceConfiguration token="vsrc1">
          <tt:Name>VideoSource1</tt:Name>
          <tt:UseCount>1</tt:UseCount>
          <tt:SourceToken>vsrc1</tt:SourceToken>
          <tt:Bounds x="0" y="0" width="1280" height="720"></tt:Bounds>
        </tt:VideoSourceConfiguration>
        <tt:VideoEncoderConfiguration token="venc1">
          <tt:Name>VideoEncoder1</tt:Name>
          <tt:UseCount>1</tt:UseCount>
          <tt:Encoding>H264</tt:Encoding>
          <tt:Resolution>
            <tt:Width>1280</tt:Width>
            <tt:Height>720</tt:Height>
          </tt:Resolution>
          <tt:Quality>50</tt:Quality>
          <tt:RateControl>
            <tt:FrameRateLimit>30</tt:FrameRateLimit>
            <tt:EncodingInterval>1</tt:EncodingInterval>
            <tt:BitrateLimit>30</tt:BitrateLimit>
          </tt:RateControl>
          <tt:H264>
            <tt:GovLength>30</tt:GovLength>
            <tt:H264Profile>Baseline</tt:H264Profile>
          </tt:H264>
          <tt:Multicast>
            <tt:Address>
              <tt:Type>IPv4</tt:Type>
              <tt:IPv4Address>0.0.0.0</tt:IPv4Address>
            </tt:Address>
            <tt:Port>0</tt:Port>
            <tt:TTL>0</tt:TTL>
            <tt:AutoStart>false</tt:AutoStart>
          </tt:Multicast>
          <tt:SessionTimeout>PT60S</tt:SessionTimeout>
        </tt:VideoEncoderConfiguration>
      </trt:Profiles>
    </trt:GetProfilesResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>"

**Comment by futomi** [comment]
You use node v0.xx, don't you? The node-onvif supports node 4.4+ for now. In near future, the node-onvif will support node 6+. I recommend node 6+.
