### ISSUE TITLE
Sending a onvif request from browser

### ISSUE THREAD

**Issue by AmdEagle** [futomi/node-onvif#9]
Is it possible to send a onvif request / response straight from the browser without going though node. I would like communicate staright with camera from the browser without going through node.js

**Comment by futomi** [comment]
I think that it's not possible.

Firstly, web browsers can't handle UPD packets directly. That is, you can't discover any onvif devices.

Secondly, web browsers can't send any HTTP requests with SOAP to cross origins even if you know the IP address of your onvif device. But if your onvif devices supports CORS, you could send HTTP requests to your onvif device. Unfortunately, I don't know onvif devices supporting CORS.

**Comment by AmdEagle** [comment]
Thank you very much for the advice
